---

    - name: Install python-pip
      apt:
        update-cache: yes
        name: python-pip
        state: present
      become: yes

    - name: Install dependencies
      pip:
        name: '{{ item }}'
        state: forcereinstall
      with_items:
        - requests
        - influxdb
        - pyOpenSSL
      become: yes


# -- Influxdata --

    - name: Import InfluxDB GPG signing key
      apt_key:
        url: "{{ influxdb_gpg_repo }}"
        state: present
      become: yes

    - name: Add InfluxDB repository
      apt_repository:
        repo: "{{ influxdb_source_repo }}"
        state: present
      become: yes

    - name: Install InfluxDB
      apt:
        update_cache: yes
        name: influxdb
        state: present
        force_apt_get: yes
      become: yes

    - name: Start InfluxDB
      service:
        name: influxdb
        state: started
        enabled: yes
      become: yes

    - name: wait
      pause: seconds=3

    - name: Replace default InfluxDB configuration file
      template:
        src: "{{ influxdb_local_config }}"
        dest: "{{ influxdb_remote_config }}"
      notify:
        - Reload InfluxDB
        - Restart InfluxDB
      become: yes

    - name: wait
      pause: seconds=3

#    - name: create user telegraf
#      command: "influx -execute \"CREATE USER {{ influxdb_telegraf_user }} WITH PASSWORD '{{ influxdb_telegraf_password }}' WITH ALL PRIVILEGES\""

#    - name: Create telegraf user
#      influxdb_user:
#        user_name: "{{ influxdb_telegraf_user }}"
#        user_password: "{{ influxdb_telegraf_password }}"
#        admin: yes
#        login_username: "{{ influxdb_telegraf_user }}"
#        login_password: "{{ influxdb_telegraf_password }}"
#        state: present
#      become: yes


# -- Telegraf --

    - name: Install Telegraf
      apt:
        update-cache: yes
        name: telegraf
        state: present
        force_apt_get: yes
      become: yes

    - name: Replace default Telegraf configuration file
      template:
        src: "{{ telegraf_local_config }}"
        dest: "{{ telegraf_remote_config }}"
      notify:
        - Reload Telegraf
        - Restart Telegraf
      become: yes

    - name: Ensure Telegraf is running
      service:
        name: telegraf
        state: started
        enabled: yes
      become: yes

# -- Grafana --

    - name: Import Grafana GPG signing key
      apt_key:
        url: "{{ grafana_gpg_repo }}"
        state: present
      become: yes

    - name: Add Grafana repository
      apt_repository:
        repo: "{{ grafana_source_repo }}"
        state: present
      become: yes

    - name: Install Grafana
      apt:
        update_cache: yes
        name: grafana
        state: present
        force_apt_get: yes
      become: yes

    - name: Replace default Grafana configuration file
      template:
        src: "{{ grafana_local_config }}"
        dest: "{{ grafana_remote_config }}"
      notify:
        - Reload Grafana
        - Restart Grafana
      become: yes

    - name: Ensure Grafana is running
      service:
        name: grafana-server
        state: started
        enabled: yes
      become: yes

    - name: Configure influxDB as a grafana datasource
      grafana_datasource:
        name: "datasource-influxdb"
        grafana_url: "{{ grafana_address }}"
#        grafana_user: "{{ influxdb_telegraf_user }}"
#        grafana_password: "{{ influxdb_telegraf_password }}"
        grafana_user: "{{ grafana_admin_user }}"
        grafana_password: "{{ grafana_admin_password }}"
        ds_type: "influxdb"
        url: "{{ influxdb_address }}"
        database: "telegraf"
        user: "{{ influxdb_telegraf_user }}"
        password: "{{ influxdb_telegraf_password }}"

#    - name: Create public dashboard
#      grafana_dashboard:
#        grafana_url: "{{ grafana_address }}"
#        grafana_user: "{{ grafana_admin_user }}"
#        grafana_password: "{{ grafana_admin_password }}"
#        state: present
#        uid: 'm5LfCz_Wz'
#        path: "{{ grafana_public_dashboard }}"
#      become: yes

#    - name: Create linux dashboard
#      grafana_dashboard:
#        grafana_url: "{{ grafana_address }}"
#        grafana_user: "{{ grafana_admin_user }}"
#        grafana_password: "{{ grafana_admin_password }}"
#        state: present
#        uid: 'ftp1S9fWz'
#        path: "{{ grafana_linux_dashboard }}"
#      become: yes

#    - name: Create windows dashboard
#      grafana_dashboard:
#        grafana_url: "{{ grafana_address }}"
#        grafana_user: "{{ grafana_admin_user }}"
#        grafana_password: "{{ grafana_admin_password }}"
#        state: present
#        uid: 'Ji3kJqBWk'
#        path: "{{ grafana_windows_dashboard }}"
#      become: yes

    - name: copu grafana dashboard json file to /tmp
      copy:
        src: "{{ grafana_dashboards_local }}/{{ grafana_public_dashboard }}"
        dest: "{{ grafana_dashboards_remote }}"
      become: yes

    - name: graf
      grafana_dashboard:
        grafana_url: "{{ grafana_address }}"
        grafana_user: "{{ grafana_admin_user }}"
        grafana_password: "{{ grafana_admin_password }}"
        state: present
        overwrite: yes
        path: "{{ grafana_dashboards_remote }}/{{ grafana_public_dashboard }}"
      become: yes

##### WEB #####

    - name: Import Nodejs GPG signin key
      apt_key:
        url: "{{ nodejs_gpg_repo }}"
        state: present
      become: yes

    - name: Install Nodejs repository
      apt_repository:
        repo: "{{ nodejs_source_repo }}"
        state: present
        update_cache: yes
      become: yes

    - name: Install Nodejs
      apt:
        update_cache: yes
        name: nodejs
        state: present
        force_apt_get: yes
      become: yes

    - stat:
        path: "{{ web_full_remote_path }}"
      register: web

    - name: Copy Web folder
      copy:
        src: "{{ web_local_path }}"
        dest: "{{ web_remote_path }}"
      when:
        - not web.stat.exists
      become: yes

#    - name: Run npm install
#      npm:
#        path: "{{ web_full_remote_path }}"

    - name: Install angular/cli
      command: npm install -g @angular/cli
      args:
        chdir: "{{ web_full_remote_path }}"
      become: yes

    - name: Install web dependencies
      npm:
        name: "{{ item }}"
        path: "{{ web_full_remote_path }}"
        state: present
      with_items:
        - 'bcryptjs'
        - 'body-parser'
        - 'cors'
        - 'dotenv'
        - 'express'
        - 'express-list-endpoints'
        - 'express-validator'
        - 'jsonwebtoken'
        - 'jwt-decode'
        - 'mysql'
        - 'morgan'
        - 'material-design-icons'
        - 'ngx-pagination'
        - 'node-fetch'
        - '@angular-devkit/build-angular'
        - '@angular/compiler-cli'
        - '@angular/compiler'
        - '@ngx-translate/core'
        - '@ngx-translate/http-loader'
      become: yes

    - name: Install forever to run nodejs as a daemon
      command: sudo npm install -g forever
      args:
        chdir: "{{ web_full_remote_path }}"
      become: yes

    - name: Create npm link to fix dependecy issues
      command: sudo npm link
      args:
        chdir: "{{ web_full_remote_path }}"
      become: yes

    - name: Install MySQL database
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
        force_apt_get: yes
      loop:
        - mysql-server
        - libmysqlclient-dev
      notify:
        - Restart MySQL
      become: yes

    - name: Ensure MySQL is running
      service:
        name: mysql
        state: started
        enabled: yes
      become: yes

    - name: Install the Python MySQLB module
      pip:
        name: MySQL-python
        state: forcereinstall
      become: yes

#    - name: Create anonymous user account for localhost
#      mysql_user:
#        name: 'root'
#        host: localhost
#        state: present

    - name: Create ESEIMS database
      mysql_db:
        name: eseims
        state: present
      become: yes

    - name: Create admin user
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: 'eseims.*:ALL,GRANT'
        state: present
      become: yes

    - name: Import eseims.sql to create database tables
      mysql_db:
        state: import
        name: eseims
        target: "{{ eseims_sql_path }}"
#      notify:
#        - Restart MySQL
      become: yes

    - name: Build web
      command: ng build
      args:
        chdir: "{{ web_full_remote_path }}"
      become: yes

    - name: run forever nodejs
      command: forever start -l eseims.log -o out.log -e err.log -a server.js
      args:
        chdir: "{{ web_full_remote_path }}"
      become: yes
