---

# -- Telegraf -- #

    - name: Import InfluxDB GPG signing key
      apt_key:
        url: "{{ influxdb_gpg_repo }}"
        state: present
      become: yes

    - name: Add InfluxDB repository
      apt_repository:
        repo: "{{ influxdb_source_repo }}"
        state: present
      become: yes

    - name: Change syslog file permissions
      file:
        path: /var/log/syslog
        mode: '0644'

    - name: Update and install telegraf
      apt:
        update-cache: yes
        name: telegraf
        state: present
        force_apt_get: yes
      become: yes

    - name: Replace default telegraf configuration file
      template:
        src: "{{ telegraf_local_config }}"
        dest: "{{ telegraf_remote_config }}"
      notify:
        - Reload Telegraf
        - Restart Telegraf
      become: yes

    - name: Ensure telegraf is running
      service:
        name: telegraf
        state: started
      become: yes

# -- Kapacitor -- #

    - name: Download Kapacitor
      get_url:
        url: "{{ kapacitor_pkg_url }}"
        dest: '/tmp'
      become: yes

    - name: Install Kapacitor
      apt:
        deb: "/tmp/{{ kapacitor_pkg }}"
      become: yes

    - name: Replace default Kapacitor config file
      template:
        src: "{{ kapacitor_local_config }}"
        dest: "{{ kapacitor_remote_config }}"
      notify:
        - Restart Kapacitor
      become: yes

    - name: Copy alarms folder
      copy:
        src: "{{ alarms_local_path }}"
        dest: "{{ alarms_remote_path_hosts }}"
      become: yes

    - name: Ensure Kapacitor is running
      service:
        name: kapacitor
        state: started
        enabled: yes
      become: yes

    - name: Alarms definition
      command: kapacitor define "{{ item }}" -tick "{{ item }}.tick"
      args:
        chdir: "{{ alarms_remote_path_hosts }}/alarms"
      loop: "{{ alarms }}"
      become: yes

    - name: Enable alarms
      command: kapacitor enable "{{ item }}"
      loop: "{{ alarms }}"
