---

    - name: Install python-pip
      apt:
        update-cache: yes
        name: python-pip
        state: present
      become: yes

# -- Influxdata --

    - name: Import InfluxDB GPG signing key
      apt_key:
        url: "{{ influxdb_gpg_repo }}"
        state: present
      become: yes

    - name: Add InfluxDB repository
      apt_repository:
        repo: "{{ influxdb_source_repo }}"
        state: present
      become: yes

# -- Telegraf --

    - name: Install Telegraf
      apt:
        update-cache: yes
        name: telegraf
        state: present
        force_apt_get: yes
      become: yes

    - name: Replace default Telegraf configuration file
      template:
        src: "{{ telegraf_local_config }}"
        dest: "{{ telegraf_remote_config }}"
      notify:
        - Restart Telegraf
      become: yes

    - name: Ensure Telegraf is running
      service:
        name: telegraf
        state: started
      become: yes

# -- InfluxDB --

    - name: Install InfluxDB
      apt:
        update_cache: yes
        name: influxdb
        state: present
        force_apt_get: yes
      become: yes

    - name: Replace default InfluxDB configuration file
      template:
        src: "{{ influxdb_local_config }}"
        dest: "{{ influxdb_remote_config }}"
      notify:
        - Restart InfluxDB
      become: yes

    - name: Install dependencies
      pip:
        name: '{{ item }}'
      with_items:
        - requests
        - influxdb

    - name: Ensure InfluxDB is running
      service:
        name: influxdb
        state: started
      become: yes

    - name: Create user Telegraf
      influxdb_user:
        user_name: "{{ influxdb_telegraf_user }}"
        user_password: "{{ influxdb_telegraf_password }}"
        admin: yes
        login_username: "{{ influxdb_telegraf_user }}"
        login_password: "{{ influxdb_telegraf_password }}"

# -- Grafana --

    - name: Import Grafana GPG signing key
      apt_key:
        url: "{{ grafana_gpg_repo }}"
        state: present
      become: yes

    - name: Add Grafana repository
      apt_repository:
        repo: "{{ grafana_source_repo }}"
        state: present
      become: yes

    - name: Install Grafana
      apt:
        update_cache: yes
        name: grafana
        state: present
        force_apt_get: yes
      become: yes

    - name: Replace default Grafana configuration file
      template:
        src: "{{ grafana_local_config }}"
        dest: "{{ grafana_remote_config }}"
      notify:
        - restart Grafana
      become: yes

    - name: Ensure Grafana is running
      service:
        name: grafana-server
        state: started
      become: yes
