---
- hosts: ubuntu-vm-test
  tasks:

    - name: Check if service telegraf exists
      stat:
        path: /lib/systemd/system/telegraf.service
      register: service_status_telegraf

    - name: Stop Telegraf
      service:
        name: telegraf
        state: stopped
      become: yes
      when:
        - service_status_telegraf.stat.exists

    - name: Remove Telegraf
      apt:
        name: telegraf
        state: absent
        purge: yes
        autoremove: yes
      become: yes
      when:
        - service_status_telegraf.stat.exists
