---
- hosts: ubuntu-server
  tasks:

    - name: Check if service telegraf exists
      stat:
        path: /lib/systemd/system/telegraf.service
      register: service_status_telegraf

    - name: Stop Telegraf
      service:
        name: telegraf
        state: stopped
      become: yes
      when:
        - service_status_telegraf.stat.exists
      register: service_stopped

    - name: Remove Telegraf
      apt:
        name: telegraf
        state: absent
        purge: yes
        autoremove: yes
      become: yes
      when:
        - service_status_telegraf.stat.exists

    - name: Check if service influxdb exists
      stat:
        path: /lib/systemd/system/influxdb.service
      register: service_status_influxdb

    - name: Stop InfluxDB
      service:
        name: influxdb
        state: stopped
      become: yes
      when:
        - service_status_influxdb.stat.exists

    - name: Remove InfluxDB
      apt:
        name: influxdb
        state: absent
        purge: yes
        autoremove: yes
      become: yes
      when:
        - service_status_influxdb.stat.exists

    - name: Check if service grafana exists
      stat:
        path: /usr/lib/systemd/system/grafana-server.service
      register: service_status_grafana

    - name: Stop Grafana
      service:
        name: grafana-server
        state: stopped
      become: yes
      when:
        - service_status_grafana.stat.exists

    - name: Remove Grafana
      apt:
        name: grafana
        state: absent
        purge: yes
        autoremove: yes
      become: yes
      when:
        - service_status_grafana.stat.exists
