---
- hosts: windows-vm
  tasks:

    - name: Check if service telegraf exists
      win_service:
        name: Telegraf
      register: service_status_telegraf

    - name: Stop Telegraf
      win_service:
        name: Telegraf
        state: stopped
      when:
        - service_status_telegraf.exists

    - name: Uninstall Telegraf service
      win_command: telegraf.exe --service uninstall
      args:
        chdir: C:\Telegraf\telegraf\
      when:
        - service_status_telegraf.exists

    - name: Remove Telegraf
      win_service:
        name: Telegraf
        state: absent
        dependency_action: remove
      when:
        - service_status_telegraf.exists

    - name: Remove telegraf directory
      win_file:
        path: C:\Telegraf
        state: absent
      when:
        - service_status_telegraf.exists

# This taks will fix the error 'registry key already exists'
#    - name: Remove registy key
#      win_regedit:
#        path: HKLM:\SYSTEM\CurrentControlSet\Services\EventLog\Application\telegraf
#        state: absent
#        delete_key: yes
