---
# handlers file for ESEIMS-provisioning

- name: "Restart Telegraf"
  service:
    name: telegraf
    state: restarted
    enabled: yes
  become: yes

- name: "Reload Telegraf"
  service:
    name: telegraf
    state: reloaded
    enabled: yes
  become: yes

- name: "Restart Telegraf Windows"
  win_service:
    name: Telegraf
    start_mode: auto
    state: restarted

- name: "Restart InfluxDB"
  service:
    name: influxdb
    state: restarted
    enabled: yes
  become: yes

- name: "Reload InfluxDB"
  service:
    name: influxdb
    state: reloaded
    enabled: yes
  become: yes

- name: "Restart Grafana"
  service:
    name: grafana-server
    state: restarted
    enabled: yes
  become: yes

- name: "Reload Grafana"
  service:
    name: grafana-server
    state: reloaded
    enabled: yes
  become: yes

- name: "Restart MySQL"
  service:
    name: mysql
    state: restarted
    enabled: yes
  become: yes

- name: "Reload MySQL"
  service:
    name: mysql
    state: reloaded
    enabled: yes
  become: yes
